DJANGO_SECRET_KEY=replace-with-a-long-random-value
DJANGO_DEBUG=true
DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
DJANGO_CSRF_TRUSTED_ORIGINS=
DATABASE_URL=sqlite:///db.sqlite3
GEMINI_API_KEY=
GEMINI_MODEL=
DEMO_VIDEO_ID=
