SOURCES = {
    "cultural_foundations": {
        "title": "From Farm, Forest, Coast and Savannah: The Cultural Foundations of Ghanaian Cuisine",
        "url": "https://ghanaculture.gov.gh/from-farm-forest-coast-and-savannah-the-cultural-foundations-of-ghanaian-cuisine/",
        "publisher": "National Commission on Culture, Ghana",
        "citation": "National Commission on Culture, Ghana. From Farm, Forest, Coast and Savannah.",
    },
    "regional_diversity": {
        "title": "Regional Representation and Diversity",
        "url": "https://ghanaculture.gov.gh/regional-representation-and-diversity/",
        "publisher": "National Commission on Culture, Ghana",
        "citation": "National Commission on Culture, Ghana. Regional Representation and Diversity.",
    },
    "ministry_culture": {
        "title": "Culture — Food and Ceremonies",
        "url": "https://www.motac.gov.gh/culture/",
        "publisher": "Ministry of Tourism, Culture & Creative Arts, Ghana",
        "citation": "Ministry of Tourism, Culture & Creative Arts, Ghana. Culture: Food and Ceremonies.",
    },
    "akplijii": {
        "title": "Traditional Foods: Akplijii, Aprapransa and Akpledze",
        "url": "https://www.motac.gov.gh/en/wp-content/uploads/Traditional_Foods_Akplijii_Aprapransa_and_Akpledze.pdf",
        "publisher": "Ministry of Tourism, Culture & Creative Arts, Ghana",
        "citation": "Ministry of Tourism, Culture & Creative Arts, Ghana. Traditional Foods: Akplijii, Aprapransa and Akpledze.",
    },
}


DISHES = [
    {
        "name": "Ga Kenkey",
        "alternative_names": ["Komi", "Kɔmi"],
        "category": "Fermented maize staple",
        "location": "Greater Accra",
        "description": "A fermented-maize staple documented as a distinct part of Ga coastal food culture.",
        "source": "cultural_foundations",
        "locator": "Food landscapes and community knowledge",
        "excerpt": "Ga kenkey ... komi",
    },
    {
        "name": "Fante Kenkey",
        "alternative_names": ["Dokono"],
        "category": "Fermented maize staple",
        "location": "Central Region",
        "description": "A fermented-maize staple documented in Fante coastal communities with its own preparation tradition.",
        "source": "cultural_foundations",
        "locator": "Food landscapes and community knowledge",
        "excerpt": "Fante kenkey ... dokono",
    },
    {
        "name": "Kpokpoi",
        "alternative_names": ["Kpekple"],
        "category": "Festival dish",
        "location": "Greater Accra",
        "description": "A maize-based food closely associated with Homowo and collective remembrance.",
        "source": "cultural_foundations",
        "locator": "Food as ceremony, memory and moral education",
        "excerpt": "kpokpoi or kpekple",
    },
    {
        "name": "Akple",
        "alternative_names": [],
        "category": "Maize staple",
        "location": "Volta Region",
        "description": "A maize-dough staple documented in Volta food traditions, often paired with okro soup.",
        "source": "cultural_foundations",
        "locator": "Food landscapes and community knowledge",
        "excerpt": "akple ... maize dough",
    },
    {
        "name": "Tuo Zaafi",
        "alternative_names": ["TZ"],
        "category": "Cereal staple",
        "location": "Northern Ghana",
        "description": "A northern Ghana staple documented with green-leaf soups in many households.",
        "source": "cultural_foundations",
        "locator": "Food landscapes and community knowledge",
        "excerpt": "Tuo zaafi ... TZ",
    },
    {
        "name": "Tubaani",
        "alternative_names": [],
        "category": "Cowpea dish",
        "location": "Northern Ghana",
        "description": "A cowpea-based food documented within northern Ghana's savannah food systems.",
        "source": "cultural_foundations",
        "locator": "Food landscapes and community knowledge",
        "excerpt": "Tubaani uses cowpea",
    },
    {
        "name": "Akyeke",
        "alternative_names": [],
        "category": "Cassava staple",
        "location": "Western Ghana",
        "description": "A cassava-based staple connected with western coastal processing knowledge.",
        "source": "cultural_foundations",
        "locator": "Food landscapes and community knowledge",
        "excerpt": "akyeke",
    },
    {
        "name": "Fufu",
        "alternative_names": [],
        "category": "Pounded staple",
        "location": "Ghana",
        "description": "A pounded staple made with plantain or tubers and commonly served with soup.",
        "source": "ministry_culture",
        "locator": "Food",
        "excerpt": "fufu, pounded plantain, or tubers",
    },
    {
        "name": "Ampesi",
        "alternative_names": [],
        "category": "Boiled staple",
        "location": "Bono and Eastern Ghana",
        "description": "A boiled yam or plantain staple represented in several forest and transition food traditions.",
        "source": "regional_diversity",
        "locator": "Regional representation",
        "excerpt": "ampesi",
    },
    {
        "name": "Eto",
        "alternative_names": ["Ɛto"],
        "category": "Mashed staple",
        "location": "Central and Western Ghana",
        "description": "A mashed staple documented in Akan food traditions and ceremonial settings.",
        "source": "regional_diversity",
        "locator": "Regional representation",
        "excerpt": "eto",
    },
    {
        "name": "Mpotompoto",
        "alternative_names": ["Mpotompotor"],
        "category": "Pottage",
        "location": "Forest and transition Ghana",
        "description": "A pottage associated with forest and transition food cultures in Ghana.",
        "source": "regional_diversity",
        "locator": "Regional representation",
        "excerpt": "mpotompoto",
    },
    {
        "name": "Akplijii",
        "alternative_names": ["Akplidzi", "Aprapransa", "Akpledze"],
        "category": "Roasted maize meal",
        "location": "Greater Accra",
        "description": "A roasted-corn-flour dish documented under different names across several Ghanaian communities.",
        "source": "akplijii",
        "locator": "Name of the element and brief description",
        "excerpt": "Akplijii ... Aprapransa ... Akpledze",
    },
]
