# Generated by Django 5.2.17 on 2026-08-20 01:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submitted_text', models.TextField()),
                ('extraction_model', models.CharField(blank=True, max_length=120)),
                ('prompt_version', models.CharField(blank=True, max_length=40)),
                ('raw_model_response', models.TextField(blank=True)),
                ('extracted_payload', models.JSONField(blank=True, null=True)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('processing_status', models.CharField(choices=[('received', 'Received'), ('extracted', 'Extracted'), ('invalid', 'Invalid model output'), ('matched', 'Potential matches generated'), ('in_review', 'In review'), ('decided', 'Decision recorded')], db_index=True, default='received', max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EvidenceExcerpt',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('locator', models.CharField(blank=True, max_length=255)),
                ('language_code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('stable_identifier', models.CharField(blank=True, max_length=255)),
                ('publisher', models.CharField(blank=True, max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(choices=[('academic', 'Academic'), ('government', 'Government'), ('institutional', 'Institutional'), ('wikidata', 'Wikidata'), ('wikipedia', 'Wikipedia'), ('book', 'Book'), ('community', 'Community'), ('culinary', 'Culinary publication'), ('other', 'Other')], max_length=20)),
                ('source_tier', models.CharField(choices=[('A', 'Tier A'), ('B', 'Tier B'), ('C', 'Tier C'), ('D', 'Tier D — discovery only')], max_length=1)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('retrieved_at', models.DateTimeField()),
                ('licence_name', models.CharField(blank=True, max_length=120)),
                ('licence_url', models.URLField(blank=True, max_length=1000)),
                ('citation_text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('publication_status', models.CharField(choices=[('draft', 'Draft'), ('review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='dishes.dishcategory')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DishClaim',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claim_type', models.CharField(choices=[('description', 'Description'), ('name_equivalence', 'Name equivalence'), ('location', 'Location association'), ('category', 'Category'), ('ingredient_mention', 'Ingredient mention'), ('relationship', 'Dish relationship'), ('other', 'Other')], max_length=30)),
                ('value', models.JSONField()),
                ('review_status', models.CharField(choices=[('extracted', 'Extracted'), ('needs_evidence', 'Needs evidence'), ('reviewed', 'Reviewed'), ('corroborated', 'Corroborated'), ('contested', 'Contested'), ('rejected', 'Rejected')], default='extracted', max_length=20)),
                ('reviewer_note', models.TextField(blank=True)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='dishes.dish')),
                ('evidence', models.ManyToManyField(related_name='claims', to='dishes.evidenceexcerpt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location_type', models.CharField(choices=[('continent', 'Continent'), ('country', 'Country'), ('region', 'Region'), ('locality', 'Locality'), ('community', 'Community')], max_length=20)),
                ('iso_code', models.CharField(blank=True, max_length=12)),
                ('wikidata_id', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='dishes.location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DishLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('associated_with', 'Associated with'), ('documented_in', 'Documented in'), ('commonly_consumed_in', 'Commonly consumed in'), ('claimed_origin', 'Claimed origin'), ('shared_across', 'Shared across'), ('uncertain', 'Uncertain')], max_length=30)),
                ('review_status', models.CharField(choices=[('extracted', 'Extracted'), ('needs_evidence', 'Needs evidence'), ('reviewed', 'Reviewed'), ('corroborated', 'Corroborated'), ('contested', 'Contested'), ('rejected', 'Rejected')], default='extracted', max_length=20)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='dishes.dish')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dish_associations', to='dishes.location')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('approve_new', 'Approve as new dish'), ('link_existing', 'Link to existing dish'), ('approve_variant', 'Approve as variant'), ('approve_related', 'Approve as related'), ('edit_approve', 'Edit and approve'), ('reject', 'Reject'), ('needs_evidence', 'Needs more evidence')], max_length=24)),
                ('notes', models.TextField(blank=True)),
                ('corrected_payload', models.JSONField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to='dishes.candidaterecord')),
                ('resulting_dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='review_decisions', to='dishes.dish')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dish_review_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='evidenceexcerpt',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='excerpts', to='dishes.source'),
        ),
        migrations.AddField(
            model_name='candidaterecord',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='candidates', to='dishes.source'),
        ),
        migrations.CreateModel(
            name='CandidateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_decision', models.CharField(choices=[('new_dish', 'New dish'), ('same_dish', 'Same dish'), ('regional_variant', 'Regional variant'), ('related_dish', 'Related dish'), ('uncertain', 'Uncertain')], max_length=24)),
                ('deterministic_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('model_score', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('model_identifier', models.CharField(blank=True, max_length=120)),
                ('rationale', models.TextField(blank=True)),
                ('evidence_summary', models.JSONField(blank=True, default=list)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_suggestions', to='dishes.candidaterecord')),
                ('proposed_dish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_matches', to='dishes.dish')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('candidate', 'proposed_dish', 'proposed_decision'), name='unique_candidate_match_suggestion')],
            },
        ),
        migrations.CreateModel(
            name='DishName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('normalized_name', models.CharField(db_index=True, max_length=200)),
                ('language_code', models.CharField(blank=True, max_length=20)),
                ('script', models.CharField(blank=True, max_length=50)),
                ('name_type', models.CharField(choices=[('canonical', 'Canonical'), ('alternative', 'Alternative'), ('local', 'Local'), ('historical', 'Historical'), ('abbreviation', 'Abbreviation')], max_length=20)),
                ('is_preferred', models.BooleanField(default=False)),
                ('review_status', models.CharField(choices=[('extracted', 'Extracted'), ('needs_evidence', 'Needs evidence'), ('reviewed', 'Reviewed'), ('corroborated', 'Corroborated'), ('contested', 'Contested'), ('rejected', 'Rejected')], default='extracted', max_length=20)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='dishes.dish')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dish', 'normalized_name', 'language_code', 'name_type'), name='unique_dish_name_form')],
            },
        ),
        migrations.CreateModel(
            name='DishRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship_type', models.CharField(choices=[('variant_of', 'Variant of'), ('related_to', 'Related to'), ('served_with', 'Served with'), ('derived_from', 'Derived from'), ('uncertain', 'Uncertain relationship')], max_length=24)),
                ('review_status', models.CharField(choices=[('extracted', 'Extracted'), ('needs_evidence', 'Needs evidence'), ('reviewed', 'Reviewed'), ('corroborated', 'Corroborated'), ('contested', 'Contested'), ('rejected', 'Rejected')], default='extracted', max_length=20)),
                ('source_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='dishes.dish')),
                ('target_dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='dishes.dish')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('source_dish', models.F('target_dish')), _negated=True), name='prevent_self_dish_relationship'), models.UniqueConstraint(fields=('source_dish', 'target_dish', 'relationship_type'), name='unique_dish_relationship')],
            },
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(fields=('name', 'location_type', 'parent'), name='unique_location_within_parent'),
        ),
        migrations.AddConstraint(
            model_name='dishlocation',
            constraint=models.UniqueConstraint(fields=('dish', 'location', 'relationship'), name='unique_dish_location_relationship'),
        ),
    ]
